### ISSUE TITLE
处理MCS服务工单时，开通服务时报错

### ISSUE THREAD

**Issue by yuanhj3** [AIPaaS/RMC#13]
处理MCS服务工单时，开通服务时报错，信息如下：

tstccs02test10@airdc-kxelr01-db02:/aifs01/tstccs02test10> tail -200f zookeeper.out 
2016-01-18 15:08:37,022 [myid:] - INFO  [main:QuorumPeerConfig@103] - Reading configuration from: /aifs01/tstccs02test10/zk_20160118150751/zookeeper-3.4.7/bin/../conf/zoo.cfg
2016-01-18 15:08:37,041 [myid:] - INFO  [main:QuorumPeer$QuorumServer@149] - Resolved hostname: 10.1.228.199 to address: /10.1.228.199
2016-01-18 15:08:37,041 [myid:] - INFO  [main:QuorumPeer$QuorumServer@149] - Resolved hostname: 10.1.228.202 to address: /10.1.228.202
2016-01-18 15:08:37,042 [myid:] - INFO  [main:QuorumPeer$QuorumServer@149] - Resolved hostname: 10.1.228.200 to address: /10.1.228.200
2016-01-18 15:08:37,042 [myid:] - INFO  [main:QuorumPeerConfig@331] - Defaulting to majority quorums
2016-01-18 15:08:37,044 [myid:] - ERROR [main:QuorumPeerMain@85] - Invalid config, exiting abnormally
org.apache.zookeeper.server.quorum.QuorumPeerConfig$ConfigException: Error processing /aifs01/tstccs02test10/zk_20160118150751/zookeeper-3.4.7/bin/../conf/zoo.cfg
        at org.apache.zookeeper.server.quorum.QuorumPeerConfig.parse(QuorumPeerConfig.java:123)
        at org.apache.zookeeper.server.quorum.QuorumPeerMain.initializeAndRun(QuorumPeerMain.java:101)
        at org.apache.zookeeper.server.quorum.QuorumPeerMain.main(QuorumPeerMain.java:78)
Caused by: java.lang.IllegalArgumentException: /home/tstccs02test10/zk_20160118150751/zookeeper-3.4.7/zk-data/myid file is missing
        at org.apache.zookeeper.server.quorum.QuorumPeerConfig.parseProperties(QuorumPeerConfig.java:341)
        at org.apache.zookeeper.server.quorum.QuorumPeerConfig.parse(QuorumPeerConfig.java:119)
        ... 2 more
Invalid config, exiting abnormally

**Comment by yuanhj3** [comment]
已修改
