### ISSUE TITLE
♣ dss页面提示服务开通成功，后场报认证失败

### ISSUE THREAD

**Issue by sunhongzhen** [AIPaaS/RMC#20]
2016-01-19 16:31:42,954 [http-nio-29888-exec-13] INFO  com.ai.paas.ipaas.rmc.manager.impl.serviceManagerImpl(72) - masseg for report openReslut: {"userId":"ADC137C6AF4D40F0B004CE7D4806C5ED","serviceId":"DSS100","resultCode":"000000","resultMsg":"Apply DSS successful!"}
2016-01-19 16:31:42,956 [http-nio-29888-exec-13] INFO  com.ai.paas.ipaas.rmc.manager.impl.serviceManagerImpl(80) - 订单处理完成
2016-01-19 16:31:52,014 [cluster-ClusterId{value='569df46d32a82f386870b335', description='null'}-10.1.228.200:48023] INFO  org.mongodb.driver.connection(71) - Opened connection [connectionId{localValue:19, serverValue:21}] to 10.1.228.200:48023
2016-01-19 16:31:52,017 [cluster-ClusterId{value='569df46d32a82f386870b335', description='null'}-10.1.228.200:48023] INFO  org.mongodb.driver.cluster(76) - Exception in monitor thread while connecting to server 10.1.228.200:48023
com.mongodb.MongoSecurityException: Exception authenticating MongoCredential{mechanism=null, userName='ADC137C6AF4D40F0B004CE7D4806C5ED', source='ADC137C6AF4D40F0B004CE7D4806C5ED', password=<hidden>, mechanismProperties={}}
        at com.mongodb.connection.SaslAuthenticator.authenticate(SaslAuthenticator.java:61) ~[mongo-java-driver-3.0.2.jar:?]
        at com.mongodb.connection.DefaultAuthenticator.authenticate(DefaultAuthenticator.java:32) ~[mongo-java-driver-3.0.2.jar:?]
        at com.mongodb.connection.InternalStreamConnectionInitializer.authenticateAll(InternalStreamConnectionInitializer.java:99) ~[mongo-java-driver-3.0.2.jar:?]
        at com.mongodb.connection.InternalStreamConnectionInitializer.initialize(InternalStreamConnectionInitializer.java:44) ~[mongo-java-driver-3.0.2.jar:?]
        at com.mongodb.connection.InternalStreamConnection.open(InternalStreamConnection.java:115) ~[mongo-java-driver-3.0.2.jar:?]
        at com.mongodb.connection.DefaultServerMonitor$ServerMonitorRunnable.run(DefaultServerMonitor.java:127) [mongo-java-driver-3.0.2.jar:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.7.0_71]
Caused by: com.mongodb.MongoCommandException: Command failed with error 18: 'Authentication failed.' on server 10.1.228.200:48023. The full response is { "ok" : 0.0, "code" : 18, "errmsg" : "Authentication failed." }
        at com.mongodb.connection.CommandHelper.createCommandFailureException(CommandHelper.java:168) ~[mongo-java-driver-3.0.2.jar:?]
        at com.mongodb.connection.CommandHelper.receiveCommandResult(CommandHelper.java:123) ~[mongo-java-driver-3.0.2.jar:?]
        at com.mongodb.connection.CommandHelper.executeCommand(CommandHelper.java:32) ~[mongo-java-driver-3.0.2.jar:?]
        at com.mongodb.connection.SaslAuthenticator.sendSaslStart(SaslAuthenticator.java:95) ~[mongo-java-driver-3.0.2.jar:?]
        at com.mongodb.connection.SaslAuthenticator.authenticate(SaslAuthenticator.java:45) ~[mongo-java-driver-3.0.2.jar:?]
        ... 6 more

**Comment by sunhongzhen** [comment]
待处理工单的用户，不能重复。内部zookeeper有记忆。
