### ISSUE TITLE
♣DBS服务，安装软件（2台机，每台机上装了2个Mysql）时报错，报错信息见描述

### ISSUE THREAD

**Issue by yuanhj3** [AIPaaS/RMC#29]
2016-01-29 11:00:47,934 [http-nio-29888-exec-8] ERROR com.ai.paas.ipaas.rms.util.HttpClientUtil(45) - *************************[{"message": "all hosts commands are executed.", "result": "True"}]*************************
2016-01-29 11:00:47,955 [http-nio-29888-exec-8] ERROR com.ai.paas.ipaas.rms.util.HttpClientUtil(30) - *************************{"data":[{"ip":"10.1.228.200","username":"tstdbs02test200"}],"dir":"sed -i \"s/47000/31382/g\" ~/my.cnf"}*************************
HTTP/1.1 200 OK [Server: nginx/1.4.4, Date: Fri, 29 Jan 2016 03:00:13 GMT, Content-Type: text/html; charset=utf-8, Transfer-Encoding: chunked, Connection: keep-alive]
2016-01-29 11:00:50,346 [http-nio-29888-exec-8] ERROR com.ai.paas.ipaas.rms.util.HttpClientUtil(45) - *************************[{"username": "tstdbs02test200", "ip": "10.1.228.200", "result": "Failed"}]*************************
2016-01-29 11:00:50,350 [http-nio-29888-exec-8] ERROR com.ai.paas.ipaas.rmc.manager.impl.ServiceInstallManagerImpl(699) - do shell 4------>failed
java.lang.Exception: do shell 4------>failed
        at com.ai.paas.ipaas.rmc.software.service.impl.SoftwareSetupUtil.chkLog(SoftwareSetupUtil.java:44) ~[ipaas-rmc-0.1-SNAPSHOT.jar:?]
        at com.ai.paas.ipaas.rmc.software.service.impl.MysqlSoftwareSvImpl.doSetup(MysqlSoftwareSvImpl.java:168) ~[ipaas-rmc-0.1-SNAPSHOT.jar:?]
        at com.ai.paas.ipaas.rmc.software.service.impl.MysqlSoftwareSvImpl.setup(MysqlSoftwareSvImpl.java:44) ~[ipaas-rmc-0.1-SNAPSHOT.jar:?]
        at com.ai.paas.ipaas.rmc.manager.impl.ServiceInstallManagerImpl.installMysql(ServiceInstallManagerImpl.java:696) [ipaas-rmc-0.1-SNAPSHOT.jar:?]
        at com.ai.paas.ipaas.rmc.manager.impl.ServiceInstallManagerImpl.create(ServiceInstallManagerImpl.java:168) [ipaas-rmc-0.1-SNAPSHOT.jar:?]
        at com.alibaba.dubbo.common.bytecode.Wrapper39.invokeMethod(Wrapper39.java) [dubbox-2.8.3.jar:2.8.3]
        at com.alibaba.dubbo.rpc.proxy.javassist.JavassistProxyFactory$1.doInvoke(JavassistProxyFactory.java:46) [dubbox-2.8.3.jar:2.8.3]
        at com.alibaba.dubbo.rpc.proxy.AbstractProxyInvoker.invoke(AbstractProxyInvoker.java:72) [dubbox-2.8.3.jar:2.8.3]
        at com.alibaba.dubbo.rpc.protocol.InvokerWrapper.invoke(InvokerWrapper.java:53) [dubbox-2.8.3.jar:2.8.3]
        at com.alibaba.dubbo.rpc.filter.ExceptionFilter.invoke(ExceptionFilter.java:64) [dubbox-2.8.3.jar:2.8.3]
        at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:91) [dubbox-2.8.3.jar:2.8.3]
        at com.alibaba.dubbo.rpc.filter.TimeoutFilter.invoke(TimeoutFilter.java:42) [dubbox-2.8.3.jar:2.8.3]
        at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:91) [dubbox-2.8.3.jar:2.8.3]
        at com.alibaba.dubbo.monitor.support.MonitorFilter.invoke(MonitorFilter.java:75) [dubbox-2.8.3.jar:2.8.3]
        at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:91) [dubbox-2.8.3.jar:2.8.3]
        at com.alibaba.dubbo.rpc.protocol.dubbo.filter.TraceFilter.invoke(TraceFilter.java:78) [dubbox-2.8.3.jar:2.8.3]
        at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:91) [dubbox-2.8.3.jar:2.8.3]
        at com.alibaba.dubbo.rpc.filter.ContextFilter.invoke(ContextFilter.java:60) [dubbox-2.8.3.jar:2.8.3]
        at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:91) [dubbox-2.8.3.jar:2.8.3]
        at com.alibaba.dubbo.rpc.filter.GenericFilter.invoke(GenericFilter.java:132) [dubbox-2.8.3.jar:2.8.3]
        at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:91) [dubbox-2.8.3.jar:2.8.3]
        at com.alibaba.dubbo.rpc.filter.ClassLoaderFilter.invoke(ClassLoaderFilter.java:38) [dubbox-2.8.3.jar:2.8.3]
        at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:91) [dubbox-2.8.3.jar:2.8.3]
        at com.alibaba.dubbo.rpc.filter.EchoFilter.invoke(EchoFilter.java:38) [dubbox-2.8.3.jar:2.8.3]
        at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:91) [dubbox-2.8.3.jar:2.8.3]
        at com.alibaba.dubbo.rpc.proxy.InvokerInvocationHandler.invoke(InvokerInvocationHandler.java:52) [dubbox-2.8.3.jar:2.8.3]
        at com.alibaba.dubbo.common.bytecode.proxy20.create(proxy20.java) [dubbox-2.8.3.jar:2.8.3]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_71]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[?:1.7.0_71]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.7.0_71]
        at java.lang.reflect.Method.invoke(Method.java:606) ~[?:1.7.0_71]

**Comment by yuanhj3** [comment]
另一种报错信息如下：
HTTP/1.1 200 OK [Server: nginx/1.4.4, Date: Mon, 01 Feb 2016 05:21:40 GMT, Content-Type: text/html; charset=utf-8, Transfer-Encoding: chunked, Connection: keep-alive]
2016-02-01 13:22:16,706 [http-nio-29888-exec-1] ERROR com.ai.paas.ipaas.rms.util.HttpClientUtil(45) - *************************[{"message": "all hosts commands are executed.", "result": "True"}]*************************
2016-02-01 13:22:16,714 [http-nio-29888-exec-1] ERROR com.ai.paas.ipaas.rms.util.HttpClientUtil(30) - *************************{"data":[{"ip":"10.1.228.200","username":"tstdbs02test201"},{"ip":"10.1.228.200","username":"tstdbs02test201"},{"ip":"10.1.228.202","username":"tstdbs02test201"},{"ip":"10.1.228.202","username":"tstdbs02test201"}],"dir":"mkdir ~/mysql_2016020113184431384"}*************************
HTTP/1.1 200 OK [Server: nginx/1.4.4, Date: Mon, 01 Feb 2016 05:21:43 GMT, Content-Type: text/html; charset=utf-8, Transfer-Encoding: chunked, Connection: keep-alive]
2016-02-01 13:22:19,657 [http-nio-29888-exec-1] ERROR com.ai.paas.ipaas.rms.util.HttpClientUtil(45) - *************************[{"username": "tstdbs02test201", "ip": "10.1.228.200", "result": "Failed"}, {"username": "tstdbs02test201", "ip": "10.1.228.200", "result": "Failed"}, {"username": "tstdbs02test201", "ip": "10.1.228.202", "result": "Failed"}, {"username": "tstdbs02test201", "ip": "10.1.228.202", "result": "Failed"}]*************************
2016-02-01 13:22:19,667 [http-nio-29888-exec-1] ERROR com.ai.paas.ipaas.rmc.manager.impl.ServiceInstallManagerImpl(654) - do shell 1------>failed
java.lang.Exception: do shell 1------>failed
        at com.ai.paas.ipaas.rmc.software.service.impl.SoftwareSetupUtil.chkLog(SoftwareSetupUtil.java:44) ~[ipaas-rmc-0.1-SNAPSHOT.jar:?]
        at com.ai.paas.ipaas.rmc.software.service.impl.MysqlSoftwareSvImpl.doSetup(MysqlSoftwareSvImpl.java:142) ~[ipaas-rmc-0.1-SNAPSHOT.jar:?]
        at com.ai.paas.ipaas.rmc.software.service.impl.MysqlSoftwareSvImpl.setup(MysqlSoftwareSvImpl.java:44) ~[ipaas-rmc-0.1-SNAPSHOT.jar:?]
        at com.ai.paas.ipaas.rmc.manager.impl.ServiceInstallManagerImpl.installMysql(ServiceInstallManagerImpl.java:651) [ipaas-rmc-0.1-SNAPSHOT.jar:?]
        at com.ai.paas.ipaas.rmc.manager.impl.ServiceInstallManagerImpl.create(ServiceInstallManagerImpl.java:180) [ipaas-rmc-0.1-SNAPSHOT.jar:?]
        at com.alibaba.dubbo.common.bytecode.Wrapper39.invokeMethod(Wrapper39.java) [dubbox-2.8.3.jar:2.8.3]
        at com.alibaba.dubbo.rpc.proxy.javassist.JavassistProxyFactory$1.doInvoke(JavassistProxyFactory.java:46) [dubbox-2.8.3.jar:2.8.3]
        at com.alibaba.dubbo.rpc.proxy.AbstractProxyInvoker.invoke(AbstractProxyInvoker.java:72) [dubbox-2.8.3.jar:2.8.3]
        at com.alibaba.dubbo.rpc.protocol.InvokerWrapper.invoke(InvokerWrapper.java:53) [dubbox-2.8.3.jar:2.8.3]
        at com.alibaba.dubbo.rpc.filter.ExceptionFilter.invoke(ExceptionFilter.java:64) [dubbox-2.8.3.jar:2.8.3]
        at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:91) [dubbox-2.8.3.jar:2.8.3]
        at com.alibaba.dubbo.rpc.filter.TimeoutFilter.invoke(TimeoutFilter.java:42) [dubbox-2.8.3.jar:2.8.3]
        at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:91) [dubbox-2.8.3.jar:2.8.3]
        at com.alibaba.dubbo.monitor.support.MonitorFilter.invoke(MonitorFilter.java:75) [dubbox-2.8.3.jar:2.8.3]
        at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:91) [dubbox-2.8.3.jar:2.8.3]
        at com.alibaba.dubbo.rpc.protocol.dubbo.filter.TraceFilter.invoke(TraceFilter.java:78) [dubbox-2.8.3.jar:2.8.3]
        at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:91) [dubbox-2.8.3.jar:2.8.3]
        at com.alibaba.dubbo.rpc.filter.ContextFilter.invoke(ContextFilter.java:60) [dubbox-2.8.3.jar:2.8.3]
        at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:91) [dubbox-2.8.3.jar:2.8.3]
        at com.alibaba.dubbo.rpc.filter.GenericFilter.invoke(GenericFilter.java:132) [dubbox-2.8.3.jar:2.8.3]
        at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:91) [dubbox-2.8.3.jar:2.8.3]
        at com.alibaba.dubbo.rpc.filter.ClassLoaderFilter.invoke(ClassLoaderFilter.java:38) [dubbox-2.8.3.jar:2.8.3]
        at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:91) [dubbox-2.8.3.jar:2.8.3]
        at com.alibaba.dubbo.rpc.filter.EchoFilter.invoke(EchoFilter.java:38) [dubbox-2.8.3.jar:2.8.3]
        at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:91) [dubbox-2.8.3.jar:2.8.3]
        at com.alibaba.dubbo.rpc.proxy.InvokerInvocationHandler.invoke(InvokerInvocationHandler.java:52) [dubbox-2.8.3.jar:2.8.3]
        at com.alibaba.dubbo.common.bytecode.proxy20.create(proxy20.java) [dubbox-2.8.3.jar:2.8.3]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_71]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[?:1.7.0_71]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.7.0_71]
        at java.lang.reflect.Method.invoke(Method.java:606) ~[?:1.7.0_71]
        at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:137) [resteasy-jaxrs-3.0.11.Final.jar:?]
        at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:296) [resteasy-jaxrs-3.0.11.Final.jar:?]
        at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:250) [resteasy-jaxrs-3.0.11.Final.jar:?]
        at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:237) [resteasy-jaxrs-3.0.11.Final.jar:?]
        at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:356) [resteasy-jaxrs-3.0.11.Final.jar:?]
        at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:179) [resteasy-jaxrs-3.0.11.Final.jar:?]
        at org.jboss.resteasy.plugins.server.servlet.ServletContainerDispatcher.service(ServletContainerDispatcher.java:220) [resteasy-jaxrs-3.0.11.Final.jar:?]
        at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:56) [resteasy-jaxrs-3.0.11.Final.jar:?]
        at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:51) [resteasy-jaxrs-3.0.11.Final.jar:?]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790) [javax.servlet-api-3.1.0.jar:3.1.0]
        at com.alibaba.dubbo.rpc.protocol.rest.DubboHttpServer$RestHandler.handle(DubboHttpServer.java:86) [dubbox-2.8.3.jar:2.8.3]
        at com.alibaba.dubbo.remoting.http.servlet.DispatcherServlet.service(DispatcherServlet.java:64) [dubbox-2.8.3.jar:2.8.3]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790) [javax.servlet-api-3.1.0.jar:3.1.0]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:291) [tomcat-embed-core-8.0.21.jar:8.0.21]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [tomcat-embed-core-8.0.21.jar:8.0.21]
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219) [tomcat-embed-core-8.0.21.jar:8.0.21]
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106) [tomcat-embed-core-8.0.21.jar:8.0.21]
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502) [tomcat-embed-core-8.0.21.jar:8.0.21]
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:142) [tomcat-embed-core-8.0.21.jar:8.0.21]
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79) [tomcat-embed-core-8.0.21.jar:8.0.21]
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88) [tomcat-embed-core-8.0.21.jar:8.0.21]
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:518) [tomcat-embed-core-8.0.21.jar:8.0.21]
        at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1091) [tomcat-embed-core-8.0.21.jar:8.0.21]
        at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:668) [tomcat-embed-core-8.0.21.jar:8.0.21]
        at org.apache.coyote.http11.Http11NioProtocol$Http11ConnectionHandler.process(Http11NioProtocol.java:223) [tomcat-embed-core-8.0.21.jar:8.0.21]
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1517) [tomcat-embed-core-8.0.21.jar:8.0.21]
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1474) [tomcat-embed-core-8.0.21.jar:8.0.21]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [?:1.7.0_71]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [?:1.7.0_71]
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-embed-core-8.0.21.jar:8.0.21]
        at java.lang.Thread.run(Thread.java:745) [?:1.7.0_71]
